### ISSUE TITLE
git URL is not usable when not logged in

### ISSUE THREAD

**Issue by panique** [Maximization/scaling-nodejs-with-docker#1]
Hey Maxim, excellent little repo, it was the only one that explained scaling in Docker really well! Thanks for bringing it to life ;)

I found a little issue: This line in the readme
```
git clone git@github.com:Maximization/scaling-nodejs-with-docker.git && cd scaling-nodejs-with-docker
```
didnt work for me, as it causes this error:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
To fix it, the URL needs to be this:
```
git clone https://github.com/Maximization/scaling-nodejs-with-docker.git && cd scaling-nodejs-with-docker
```
I'm intentially not commiting a pull request, as this might just be a mistake on my side (i still haven't fully understood git).

All the best

**Comment by Maximization** [comment]
@panique Happy to hear you found this repo useful!

As for cloning, the first notation `git@github.com...` uses the SSH protocol. To use this URL, you must generate an SSH keypair on your computer and add the public key to your account on GitHub. Otherwise you'll get the error you posted. More info here: https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-ssh-urls

You might not be the first to stumble upon this, so I've updated the instructions to use HTTPS as you suggested. Thank you!

**Comment by Maximization** [comment]
Coincidentally, I wrote an article (and recorded a video) showing you how to solve the "Permission denied" error from Github. In case you might want to use SSH in the future ;)

https://maximorlov.com/fix-permission-denied-error-from-github/
